#!/bin/bash
export CHROME_WRAPPER="`readlink -f "$0"`"
HERE="`dirname "$CHROME_WRAPPER"`"

export CHROME_CONFIG_HOME="$HOME/.config"

flags="--auto-select-desktop-capture-source=Schermo --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization,WebRTCPipeWireCapturer"

chrome="$HERE/chromium/chrome $flags"

function defaults {
	mkdir -p "$1/Default"
	
	if [ -f $1/Default/Preferences ]; then
		return
	fi
	
	tee "$1"/Default/Preferences <<- EOF >> /dev/null
		{"profile": {
        	"cookie_controls_mode":2,
        	"default_content_setting_values":{"cookies":1},
        	"exit_type":"Normal"
    		}}
	EOF
}

function widevineConfig {
	mkdir -p "$1"/WidevineCdm
		
	tee "$1"/WidevineCdm/latest-component-updated-widevine-cdm <<- EOF >> /dev/null
		{"Path":"$HERE/widevine"}
	EOF
}


if   [ $1 ] && ([ $1 == "--help" ] || [ $1 == "-h" ]) ; then
	
	echo "AVAIABLE OPTIONS:"        
	echo "--help   | -h                     Display this text"
	echo "--webapp | -w      [name] [url]   Launch url webapp"
	echo "--reset  | -r      [name]	        Reset webapp data"
	
elif [ $1 ] && ([ $1 == "--webapp" ] || [ $1 == "-w" ]) ; then
	
	if [ $2 ] && [ $3 ]; then
		defaults "$CHROME_CONFIG_HOME/chromeapps/$2"
		#widevineConfig "$CHROME_CONFIG_HOME/chromeapps/$2"
		
		exec $chrome --window-size=1200,800 --class=$2 --user-data-dir="$CHROME_CONFIG_HOME/chromeapps/$2" --app="$3" "${@:4}"
	else
		echo "Not enough arguments for a webapp"
	fi
	
elif [ $1 ] && ([ $1 == "--reset" ] || [ $1 == "-r" ]) ; then

	if [ $2 ] ; then
		exec rm -fr $CHROME_CONFIG_HOME/chromeapps/$2
	else
		echo "Not enough arguments to reset a webapp"
	fi
	
else
	# Just start chromium
	defaults "$CHROME_CONFIG_HOME/chromium"
	#widevineConfig "$CHROME_CONFIG_HOME/chromium"
	export CHROME_DESKTOP="ungoogled-chromium.desktop"
	
	exec $chrome --ozone-platform-hint=auto --ignore-gpu-blocklist --use-angle=none "$@"
fi
